package in.co.everyrupee.event.listener.income;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.util.MultiValueMap;

import in.co.everyrupee.events.income.OnSaveTransactionCompleteEvent;

/**
 * Bank Account Bulk Delete Listener Test (Listener)
 * 
 * @author Nagarjun
 *
 */
@RunWith(SpringRunner.class)
public class UserBudgetCreationListenerTest {

	@Autowired
	private ApplicationEventPublisher eventPublisher;

	private static final String FINANCIAL_PORTFOLIO_ID = "19300000";

	@Test
	@WithMockUser(value = "spring")
	public void saveAutoGeneratedUserBudget() {
		MultiValueMap<String, String> formData = null;
		eventPublisher.publishEvent(new OnSaveTransactionCompleteEvent(FINANCIAL_PORTFOLIO_ID, formData));
	}

}
