package in.co.everyrupee.event.listener.income;

import java.util.Map;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.context.junit4.SpringRunner;

import in.co.everyrupee.events.income.OnFetchCategoryTotalCompleteEvent;

/**
 * Bank Account Bulk Delete Listener Test (Listener)
 * 
 * @author Nagarjun
 *
 */
@RunWith(SpringRunner.class)
public class UserBudgetUpdationListenerTest {

	@Autowired
	private ApplicationEventPublisher eventPublisher;

	private static final String FINANCIAL_PORTFOLIO_ID = "19300000";

	private static final String DATE_MEANT_FOR = "01062019";

	@Test
	@WithMockUser(value = "spring")
	public void saveAutoGeneratedUserBudget() {
		Map<Integer, Double> categoryIdAndTotalAmount = null;
		eventPublisher.publishEvent(new OnFetchCategoryTotalCompleteEvent(categoryIdAndTotalAmount, DATE_MEANT_FOR,
				FINANCIAL_PORTFOLIO_ID));
	}

}
